In [1]:
import numpy as np
import numpy
import sklearn.cluster





In [2]:
import collections
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
from pprint import pprint

    

In [3]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\t_kar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\t_kar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
def word_tokenizer(text):
            #tokenizes and stems the text
    tokens = word_tokenize(text)
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(t) for t in tokens if t not in stopwords.words('english')]
    return tokens

In [5]:
def cluster_sentences(sentences, nb_of_clusters = 5):
    tfidf_vectorizer = TfidfVectorizer(tokenizer=word_tokenizer,
                                    stop_words=stopwords.words('english'),
                                     max_df=0.9,
                                    min_df=0.1,
                                    lowercase=True)
            #builds a tf-idf matrix for the sentences
    tfidf_matrix = tfidf_vectorizer.fit_transform(sentences)
    kmeans = KMeans(n_clusters=nb_of_clusters)
    kmeans.fit(tfidf_matrix)
    clusters = collections.defaultdict(list)
    for i, label in enumerate(kmeans.labels_):
            clusters[label].append(i)
    return dict(clusters)

In [9]:

sentences = []

with open('descriptions.txt', encoding = "utf8") as f:
    for line in f:
        text = line.lower()                                       ## Lowercase all characters
        text = text.replace("[comma]"," ")                        ## Replace [commas] with empty space
        for ch in text:
            if ch < "0" or (ch < "a" and ch > "9") or ch > "z":   ## The cleaning operation happens here, remove all special characters
                text = text.replace(ch," ")
        text = ' '.join(text.split())                             ## Remove double spacing from sentences
        sentences.append(text)
nclusters= 296
clusters = cluster_sentences(sentences, nclusters)
for cluster in range(nclusters):
    print ("cluster ",cluster,":")
    for i,sentence in enumerate(clusters[cluster]):
        print ("\tsentence ",i,": ",sentences[sentence])
        

cluster  0 :
	sentence  0 :  she is a bit chubby and short she isn t in the most shape and she dresses kind of like a skater or so she is nice caring and likes cats she is into classic rock and making blankets
	sentence  1 :  he has medium length hair for a boy with a slight curl to it his eyes are light and he is kind of expressionless i would guess that he is maybe in high school or recently graduated he looks like he s maybe like a band kid but with a different expression i could also picture him as a jock type he seems like he would have a larger frame
	sentence  2 :  she is well kept and attractive she does not have blemishes and wears little makeup she like children she likes to read books and drink coffee she likes to watch tv
	sentence  3 :  short stocky hair legs sometime has a beard walks with a limp likes spicy food loves his family single don t like animals
	sentence  4 :  they have medium black hair they are average weight they have a large nose they like video games they 

	sentence  3 :  she is about 5 feet 4 inches tall she needs to lose about 30 pounds she isn t completely out of shape but she does need work she s kind she is quick witted she is smart she wants to move up in her career she takes extra college courses at night
	sentence  4 :  she is 5 3 tall and weighs 185 pounds due to her job she has issues with her feet and has a slight limp she works in a manufacturing facility where she is a supervisor she works long days and stands on her feet for much of it she is married with two kids she has two sisters and a brother and her parents are still married she lives in a rural area and commutes 20 minutes to her job she likes facebook country music and having wine with friends
cluster  70 :
	sentence  0 :  this person is a very upset face and handsome face his eyes are very beautiful this person is very smart and intelligent if this person comes home there is a great peace
	sentence  1 :  this person has nice round features and is very symmetrical i

cluster  127 :
	sentence  0 :  male medium height medium build short black hair clean shaven brown eyes no visible tattoos he likes sports he likes girls he likes beer and he likes mexican food
	sentence  1 :  this woman has brown hair and it s pulled back in a bun she has blue eyes and a not so happy expression she also has some red marks on her face likely from pimples her eyebrows are short and thin she is average height with a slender build she is female she works as a waitress in a restaurant she is single and straight she doesn t like her job she seems to be in a hurry
	sentence  2 :  she is a caucasian female fair complexion brown hair brown eyes average height and build no visible tattoos she doesn t like to wear much makeup she s very calm and self possessed she doesn t like to spend much time on her hair
	sentence  3 :  he has short brown hair blue eyes fair skin and a stubbly beard he is probably of average height and build there are no visible tattoos he likes sports he lik

	sentence  2 :  this person has an athletic build is somewhat short and has tattoos he has a hip faux hawk haircut and a fairly dark complexion i guess this person is interested in women drinking and has a quick temper
	sentence  3 :  this person wears down to earth clothes in browns and greens is 5 10 average build weight this person is slightly uncoordinated and a little goofy when it comes to talking with girls
	sentence  4 :  the person had short brown hair fair skin 5 2 athletic build the person is on the student counseling board the loves to draw the person have 6 brothers and she is the only girl
	sentence  5 :  the person is slight of build and has not yet reached puberty he gets picked on in school because he is considered a sissy
	sentence  6 :  this person has an average and muscular build they are about 5 8 140 lbs they have brown hair and blue eyes and some facial blemishes this person is argumentative and combative they are athletic and competitive this person stands firm

cluster  246 :
	sentence  0 :  he has an elongated face well maintained facial hair brown hair almost in a bowl cut style medium length forehead christian here enjoys watching stoner flicks as he packs a fresh bowl after a long day at work he plays in a garage rock band and wears skater shoes
	sentence  1 :  she has dark red hair and brown eyes her eyes are a little bit off kilter and she has a bit of a vacant look did not graduate works in a service industry gets hair cut often possibly mentally slow
	sentence  2 :  thin lips brown eyes receding hairline light brown hair looks fit he looks mysterious unorthodox determined hard working manipulating and very smart
	sentence  3 :  this looks to be a woman of indian background she has brown hair and brown eyes to go with it indian smart hard working immigrant woman tough daughter sister reliable
	sentence  4 :  he has shaggy brown hair and brown eyes he has stubble also does drugs doesnt commit late for work doesnt like to shave
cluster  

In [11]:
print(clusters[0])
print()
print(clusters[295])

[51, 197, 258, 550, 655, 697, 874, 924, 927, 994, 1047, 1159, 1231, 1441, 1449]

[126, 321, 789, 1312, 1433, 1443]


[[25, 26, 27, 28, 29], [30, 32, 40, 41, 42, 44], [10, 11, 12, 13, 14], [17, 19, 24, 31, 33, 34, 43], [5, 6, 7, 8, 9], [15, 16, 18], [45, 46, 47, 48, 49], [0, 1, 2, 3, 4], [35, 36, 37, 38, 39], [20, 21, 22, 23]]


[[  0.   0.   0. ...   0.   0.   0.]
 [  1.   0.   0. ...   0.   0.   0.]
 [  2.   0.   0. ...   0.   0.   0.]
 ...
 [293.   0.   0. ...   0.   0.   0.]
 [294.   0.   0. ...   0.   0.   0.]
 [295.   0.   0. ...   0.   0.   0.]]
