In [2]:
import numpy
import scipy
import scipy.sparse
import sklearn
import sklearn.metrics.pairwise
from sklearn import datasets
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.feature_extraction.text import TfidfVectorizer


In [3]:
dataSet = numpy.load("descriptions_cleaned_array.npy")
#dataSet = dataSet[0:3]
#print(dataSet)

# Count Vectorizer
Using the Count vectorizer function which only looks at word counts

In [4]:
countVect = sklearn.feature_extraction.text.CountVectorizer()
Count_dataSet = countVect.fit_transform(dataSet)
#vectorVocab = vectorizer._validate_vocabulary()
#print(Count_dataSet.shape, Count_dataSet.size,numpy.size(Count_dataSet, axis=0),numpy.size(Count_dataSet, axis=1),,"\n")
#print(vectorizer.get_feature_names(),"\n")
#print(Count_dataSet.shape, Count_dataSet.size,,"\n")
#print(Count_dataSet)

## Cosine Similarity
Here using the cosine similarity distance measure on the Count Vectorizer matrix

In [5]:
cossim = sklearn.metrics.pairwise.cosine_similarity(Count_dataSet)
#print(cossim,,"\n")
cosineSimilaritySorted = numpy.argsort(cossim, axis=1)
#print(cosineSimilaritySorted,,"\n")
top5Similar = cosineSimilaritySorted[:,-6:-1]
print(top5Similar)



[[ 606 1315 1120 1191  495]
 [1241  401  555  268  932]
 [ 181 1173 1050  208 1132]
 ...
 [ 818 1435 1371  795 1170]
 [ 178 1094  966 1063  894]
 [ 163  602  499  546  279]]


Manual comparison shows it doesn't work great, some words are similar but then the descriptions are clearly blond hair vs black hair --> Perhaps we can try looking at sets of two words at a time

In [74]:
print(dataSet[932])
print(dataSet[268])

black hair blue eyes and no facial hair average height and athletic build enjoys sports and skate boarding is currently in college and is outgoing person is friendly and willing to help others out
caucasian male with blonde hair and blue eyes has a beard and a mustache he looks geeky kind of grumpy and maybe into technology


## Euclidean Distance
Also look at Euclidean distance which shows similar problems as cosine similiarity

In [6]:
euclid = pairwise_distances(Count_dataSet, metric='euclidean')
euclidSorted = numpy.argsort(euclid, axis=1)
top5Similar = euclidSorted[:,1:6]
print(top5Similar)


[[1350 1191  584  226 1272]
 [1241 1365 1338  222  268]
 [ 208 1125 1123   56 1326]
 ...
 [1371   56  680  581  592]
 [ 894 1094   68  178  104]
 [ 499 1143  540  279  943]]


In [77]:
print(dataSet[1241])
print(dataSet[1365])

white woman with brown hair and eyes and clear even skin upper middle class probably a democrat and a feminist
white female early 20 s with blond hair and green eyes direct personality straight forward attitude confident and honest


## Manhattan distance

In [7]:
manhat = pairwise_distances(Count_dataSet, metric='manhattan')

manhatSorted = numpy.argsort(manhat, axis=1)
top5Similar = manhatSorted[:,1:6]
print(top5Similar)


[[1453 1434  584 1331 1350]
 [ 222 1365 1241 1338  268]
 [ 208 1125  291   56  592]
 ...
 [1371   56  680  592  626]
 [ 894    3 1094  927  739]
 [ 404 1143 1206  540  984]]


In [82]:
print(dataSet[894])
print(dataSet[1094])

this person is 5 2 weighs 180 pounds her shoe size is 6 5 she enjoys reading biking and going to movies she is not married and has three cats that she calls her furbabies she is a teacher so she is very busy
she is fair complected with light freckles she has beautiful large blue eyes and full pink lips she is shy she enjoys reading she is intelligent she is compassionate


Was going to try the other distance functions on the TFID vector, but since they didn't seem to improve the count vector, then didn't bother; But now instead going to try TFID and Count Vector with 2 word items and all distance measures