In [1]:
import numpy
import scipy
import scipy.sparse
import sklearn
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.cluster import KMeans
import sklearn.metrics.pairwise

# Data cleaning

The first step of nearly any machine learning analysis project is data cleaning. This is done in order to allow a larger variety of models to work with a predictable input, such that exceptions (in this case special characters such as quotation marks, '[comma]' and others) will not cause any disturbance in the model. The following code loads the data, 'cleans' it, and afterwards sets the entire cleaned data in an array. Comments are added in the code to improve interpretability.

### Cleaning

In [2]:
## Set an empty list variable

descriptions = []

with open('descriptions.txt', encoding = "utf8") as f:
    for line in f:
        text = line.lower()                                       ## Lowercase all characters
        text = text.replace("[comma]"," ")                        ## Replace [commas] with empty space
        for ch in text:
            if ch < "0" or (ch < "a" and ch > "9") or ch > "z":   ## The cleaning operation happens here, remove all special characters
                text = text.replace(ch," ")
        text = ' '.join(text.split())                             ## Remove double spacing from sentences
        descriptions.append(text)
dataSet = numpy.array(descriptions)
f.close()

### Train set

In [3]:
descriptions2 = []

with open('coco_val.txt', encoding = "utf8") as f:
    for line in f:
        text = line.lower()                                       ## Lowercase all characters
        descriptions2.append(text.split('\n'))

trainSet = numpy.array(descriptions2)
f.close()

print(trainSet[1])
print(trainSet[2])
print(trainSet.shape)

['a young man holding an umbrella next to a herd of cattle' '']
['a young boy barefoot holding an umbrella touching the horn of a cow' '']
(25000, 2)


The data is now cleaned according to a list of lists.

In [4]:
print('The size of our data set: ', dataSet.size)
print('The dimension of our dataset are: ', dataSet.shape)
print('\n')
print('-- 0th element of our dataSet --', '\n', dataSet[0])
print('\n')
print('-- 1st element of our dataSet --', '\n', dataSet[1])

The size of our data set:  1480
The dimension of our dataset are:  (1480,)


-- 0th element of our dataSet -- 
 round face short and overweight likes to wear jeans and sweaters drinks wine at dinner short liberal overweight short hair eats at whole foods does not work our very much


-- 1st element of our dataSet -- 
 jug ears mustache and beard and long sideburns stylish hair no laugh lines eyes are clear no drugs or alcohol confident a little overweight from double chin


Since the input vector now is 'clean', different representations can be made, which in turn can then be trained to obtain accuracy measures of classification.

In [5]:
import matplotlib.pyplot as plt  
%matplotlib inline


vectorizer = CountVectorizer()
representation1 = vectorizer.fit_transform(dataSet)

In [6]:
KMeans = sklearn.cluster.KMeans(n_clusters=296)

In [7]:
KmeansFit = KMeans.fit(representation1)
labels = KMeans.predict(representation1)
C = KMeans.cluster_centers_
print(C)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
