In [94]:
import numpy
import sklearn
import sklearn.metrics.pairwise
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import LatentDirichletAllocation
import string
import collections
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
from nltk import word_tokenize
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from pprint import pprint
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/rickmackenbach/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/rickmackenbach/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [95]:
## Set an empty list variable

descriptions = []

with open('descriptions.txt', encoding = "utf8") as f:
    for line in f:
        text = line.lower()                                       ## Lowercase all characters
        text = text.replace("[comma]"," ")                        ## Replace [commas] with empty space
        for ch in text:
            if ch < "0" or (ch < "a" and ch > "9") or ch > "z":   ## The cleaning operation happens here, remove all special characters
                text = text.replace(ch," ")
        text = ' '.join(text.split())                             ## Remove double spacing from sentences
        descriptions.append(text)
dataSet = numpy.array(descriptions)

print('After running first results, the following sentence was found : ')
print()
print(dataSet[496])
print()
print()
print('Although this sentence is not meaningful, it will remain in the dataset in order to have consistent results.')

After running first results, the following sentence was found : 

rwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdc

In [96]:
vectorizer = TfidfVectorizer(max_df=0.5, min_df=2, stop_words='english', max_features=1000, use_idf=True)
TfIdf_dataSet = vectorizer.fit_transform(dataSet)

In [97]:
LSA = TruncatedSVD(100)
LSAData = LSA.fit_transform(TfIdf_dataSet)

In [98]:
cosineSimilarity = sklearn.metrics.pairwise.cosine_similarity(LSAData)
numpy.fill_diagonal(cosineSimilarity,1.1)
cosineSimilaritySorted = numpy.argsort((-1*(cosineSimilarity)),axis=1)
top5similar = (cosineSimilaritySorted[:,0:5])
print()
print(top5similar)


[[   0   66  894 1376  406]
 [   1  549  556  506  206]
 [   2  342  405  646 1388]
 ...
 [1477  392 1372  859  530]
 [1478  967  216  625  579]
 [1479  788 1341  553 1144]]


In [99]:
print(dataSet[2])
print(dataSet[342])

red hair a little lower than the ears big face a little weirdly shaped around the jaw freckles he looks like he had a hard childhood and isn t a happy person he probably has a lot of repressed feeling or the photographer didn t get him on a good day
this is a white male with red hair and blue eyes his hair is shaggy and has a little facial stubble this person is a student he might be a little over weight he looks a little angry


In [100]:
numpy.savetxt("results3.csv", top5similar.astype(int), fmt='%i', delimiter=",")