In [1]:
import numpy
import sklearn
import sklearn.metrics.pairwise
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.decomposition import TruncatedSVD
import string
import collections
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
from nltk import word_tokenize
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from pprint import pprint
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/rickmackenbach/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/rickmackenbach/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
## Set an empty list variable

descriptions = []

with open('descriptions.txt', encoding = "utf8") as f:
    for line in f:
        text = line.lower()                                       ## Lowercase all characters
        text = text.replace("[comma]"," ")                        ## Replace [commas] with empty space
        for ch in text:
            if ch < "0" or (ch < "a" and ch > "9") or ch > "z":   ## The cleaning operation happens here, remove all special characters
                text = text.replace(ch," ")
        text = ' '.join(text.split())                             ## Remove double spacing from sentences
        descriptions.append(text)
dataSet = numpy.array(descriptions)

print('After running first results, the following sentence was found : ')
print()
print(dataSet[496])
print()
print()
print('Although this sentence is not meaningful, it will remain in the dataset in order to have consistent results.')

After running first results, the following sentence was found : 

rwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewad rwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdcerfadwerfdewadrwevfderdc

In [3]:
vectorizer = TfidfVectorizer(stop_words='english')
TfIdf_dataSet = vectorizer.fit_transform(dataSet)
print("What our Tf-Idf looks like: ")
print()
print(TfIdf_dataSet[0:1])

vectorVocab = vectorizer._validate_vocabulary()

What our Tf-Idf looks like: 

  (0, 3085)	0.18016293756155294
  (0, 1351)	0.10858700066557808
  (0, 3257)	0.3001624823648848
  (0, 2585)	0.34043262183046635
  (0, 2139)	0.11306416211646501
  (0, 4024)	0.21854146699056293
  (0, 1981)	0.25581194154091114
  (0, 3626)	0.31679149916873117
  (0, 1152)	0.24315753998842082
  (0, 4070)	0.2684663430934014
  (0, 1073)	0.30413709761624086
  (0, 2120)	0.2684663430934014
  (0, 1687)	0.06619086894558779
  (0, 1200)	0.26383180239523174
  (0, 1473)	0.31679149916873117
  (0, 1117)	0.16480321090672406
  (0, 4092)	0.16167588241502212


In [6]:
svd = TruncatedSVD(n_components=100)
LSAData = svd.fit_transform(TfIdf_dataSet)

In [12]:
cosineSimilarity = sklearn.metrics.pairwise.cosine_similarity(LSAData)
numpy.fill_diagonal(cosineSimilarity,1.1)
cosineSimilaritySorted = numpy.argsort((-1*(cosineSimilarity)),axis=1)
top5similar = (cosineSimilaritySorted[:,0:5])
print()
print(top5similar)

numpy.savetxt("results2.csv", top5similar.astype(int), fmt='%i', delimiter=",")


[[   0   66  894  406  607]
 [   1  549  401  556  106]
 [   2  646  342  405 1388]
 ...
 [1477 1372  392  801  859]
 [1478  967  625  216 1146]
 [1479  788 1341  402  553]]


In [11]:
print(dataSet[0])
print()
print(dataSet[66])

round face short and overweight likes to wear jeans and sweaters drinks wine at dinner short liberal overweight short hair eats at whole foods does not work our very much

plain freckles short hair boring eyes likes earrings hair parted normally probably slightly overweight but not sure about that she likes twilight she isn t married she is sad she is slightly overweight
