In [9]:
import numpy
import sklearn
import sklearn.metrics.pairwise
from sklearn.metrics.pairwise import pairwise_distances
import string
import collections
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score

In [10]:
dataSet = numpy.load("descriptions_cleaned_array.npy")

In [11]:
vectorizer = TfidfVectorizer(stop_words='english')
TfIdf_dataSet = vectorizer.fit_transform(dataSet)

In [12]:
LSA = TruncatedSVD(100)
LSAData = LSA.fit_transform(TfIdf_dataSet)
print(LSAData.shape)

(1480, 100)


In [13]:
cosineSimilarity = sklearn.metrics.pairwise.cosine_similarity(LSAData)
numpy.fill_diagonal(cosineSimilarity,1.1)
cosineSimilaritySorted = numpy.argsort((-1*(cosineSimilarity)),axis=1)
top5similar = (cosineSimilaritySorted[:,0:5])
print()
print(top5similar)


[[   0   66  894 1221  406]
 [   1  549  556  506  181]
 [   2  342  646  564  405]
 ...
 [1477 1372  392  859  561]
 [1478  967  216  579  625]
 [1479  788 1341  155  553]]


In [14]:
print(dataSet[0])
print(dataSet[66])

round face short and overweight likes to wear jeans and sweaters drinks wine at dinner short liberal overweight short hair eats at whole foods does not work our very much
plain freckles short hair boring eyes likes earrings hair parted normally probably slightly overweight but not sure about that she likes twilight she isn t married she is sad she is slightly overweight


In [15]:
numpy.savetxt("results4.csv", top5similar.astype(int), fmt='%i', delimiter=",")