In [9]:
import numpy
import scipy
import scipy.sparse
import sklearn
import sklearn.metrics.pairwise
from sklearn import datasets
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.feature_extraction.text import TfidfVectorizer


In [11]:
dataSet = numpy.load("coco_val.npy")
#dataSet = numpy.load("descriptions_cleaned_array.npy")
#dataSet = dataSet[0:3]
#print(dataSet)

## Sets of two workds
Use regex in the tokenizer field to set a token size of 2 words instead of looking at words one at a time. Each word is in 2 sets of phrases, ex/ eats chocolate cookies -> eats chocolate & chocolate cookies
Idea is that phrases like brown eyes, blond hair will be looked at together and brown hair and brown eyes won't get matched because they both have brown in the sentences

Would also like to look at 1 and 2 word sized tokens

In [19]:
token = r"(?=\b([a-zA-Z]{2,40} [a-zA-Z]{2,40}))"  #token with exactly two works
#token =   r"(?=\b(([a-zA-Z]{2,40} ?){1,2}))" #token with 1 or two words

## Count vectorizer - 2 words

In [20]:
countVect = sklearn.feature_extraction.text.CountVectorizer(token_pattern = token)
Count_dataSet = countVect.fit_transform(dataSet)
#vectorVocab = vectorizer._validate_vocabulary()

print(countVect.get_feature_names(),"\n")
print(Count_dataSet.shape, Count_dataSet.size,"\n")
#print(Count_dataSet)

[('abandoned boat ', 'boat '), ('abandoned building', 'building'), ('abandoned bus ', 'bus '), ('abandoned in ', 'in '), ('abandoned luggage ', 'luggage '), ('abandoned on ', 'on '), ('abandoned street', 'street'), ('abandoned track', 'track'), ('abandoned train ', 'train '), ('abandoned umbrella', 'umbrella'), ('abdomen', 'abdomen'), ('abll on ', 'on '), ('aboard', 'aboard'), ('aboard ', 'aboard '), ('aboard an ', 'an '), ('abound in ', 'in '), ('about', 'about'), ('about ', 'about '), ('about animal ', 'animal '), ('about as ', 'as '), ('about half ', 'half '), ('about her ', 'her '), ('about his ', 'his '), ('about in ', 'in '), ('about motorcycles', 'motorcycles'), ('about motorcycles ', 'motorcycles '), ('about no ', 'no '), ('about on ', 'on '), ('about ready ', 'ready '), ('about set ', 'set '), ('about someone', 'someone'), ('about the ', 'the '), ('about things', 'things'), ('about to ', 'to '), ('about trains', 'trains'), ('about what ', 'what '), ('about within ', 'within ')

## Cosine similarity distance - CntVect

In [14]:
cossim = sklearn.metrics.pairwise.cosine_similarity(Count_dataSet)
#print(cossim,,"\n")
cosineSimilaritySorted = numpy.argsort(cossim, axis=1)
#print(cosineSimilaritySorted,,"\n")
top5Similar = cosineSimilaritySorted[:,-6:-1]
print(top5Similar)



[[ 4716  1119 10182 20605 11547]
 [ 3775  1813  8495 14105 14109]
 [14105  7296 10833 10830     3]
 ...
 [ 4393  4390  4392 12556  4394]
 [ 2373 20065 15212 21515  7555]
 [18417 16157 17743 24995  1510]]


Notes:

In [31]:
print(dataSet[831],"\n")
print(dataSet[1063])

she has fair skin with some freckles she has dark blue eyes she has bright red hair and eyebrows she may be a bit overweight she seems like she is educated but a bit sad she probably doesn t have very many friends but likely has pets she is probably close with her mother 

she is young in her middle twenties she has blue eyes her complexion is a little flawed she has some pimples she has very straight and thin brown hair she has thick eyebrows she has medium sized lips she is plain she is about average in looks she is just starting out in life she does not seem very ambitious she seems like she might be a little trusting and naive she is a follower she does not seem very forceful she seems like she will have a lower class job


## Euclidean distance - CntVect

In [32]:
euclid = pairwise_distances(Count_dataSet, metric='euclidean')
euclidSorted = numpy.argsort(euclid, axis=1)
top5Similar = euclidSorted[:,1:6]
print(top5Similar)


[[1350  892 1343  584  780]
 [ 892 1343  780  611 1338]
 [ 892  780  611 1343 1125]
 ...
 [  56 1371 1358  194  459]
 [1012  611 1094  980  536]
 [ 809  892  387  584  611]]


In [34]:
print(dataSet[611],"\n")
print(dataSet[387],"\n")

she looks like about 5 9 with a normal bmi i guess that she is probably a graduate student currently and works part time 

this woman is probably around 5 8 and is a bit above average weight she has a big family not easily swayed generally happy in life 



## Manhattan distance - CntVect
--very slow to run and unlikely to be better

In [ ]:
manhat = pairwise_distances(Count_dataSet, metric='manhattan')

manhatSorted = numpy.argsort(manhat, axis=1)
top5Similar = manhatSorted[:,1:6]
print(top5Similar)


In [82]:
print(dataSet[894])
print(dataSet[1094])

this person is 5 2 weighs 180 pounds her shoe size is 6 5 she enjoys reading biking and going to movies she is not married and has three cats that she calls her furbabies she is a teacher so she is very busy
she is fair complected with light freckles she has beautiful large blue eyes and full pink lips she is shy she enjoys reading she is intelligent she is compassionate


# TFID Vectorizer - 2-words

In [15]:
vectorizer = TfidfVectorizer(token_pattern = token)
TfIdf_dataSet = vectorizer.fit_transform(dataSet)
#vectorVocab = vectorizer._validate_vocabulary()

#print(countVect.get_feature_names(),"\n")
print(Count_dataSet.shape, Count_dataSet.size,"\n")
#print(TfIdf_dataSet,"\n")



(25000, 47758) 170382 



## Cosine similarity distance - TfIdf

In [16]:
cossim = sklearn.metrics.pairwise.cosine_similarity(TfIdf_dataSet)
#print(cossim,,"\n")
cosineSimilaritySorted = numpy.argsort(cossim, axis=1)
#print(cosineSimilaritySorted,,"\n")
top5Similar = cosineSimilaritySorted[:,-6:-1]
print(top5Similar)



[[ 4716 11547  4710  1119 20605]
 [21220 14076 14109 14105  8495]
 [ 3721 14109 14105 10830     3]
 ...
 [ 4390  4393 12556  4392  4394]
 [14851 18934 22739  7555 21515]
 [22092 22096 18417  5690  1510]]


Notes:

In [8]:
print(dataSet[1385],"\n")
print(dataSet[1416])

it is a blond man with blue eyes he has a small mustache and goatee he has some gel styling his hair he has blond eyebrows and facial hair his skin is fair he looks like he went to college he looks like he grew up in at least a middle class family he looks employed 

this person is 5 feet 9 inches tall he probably weighs no more than 180 he probably has an athletic build and is physically fit this person look a little lazy all in all he is probably a good person but it looks like he is immature it looks like he can be disorganized and can be unmotivated at times


## Euclidean distance - TfIdf

In [9]:
euclid = pairwise_distances(TfIdf_dataSet, metric='euclidean')
euclidSorted = numpy.argsort(euclid, axis=1)
top5Similar = euclidSorted[:,1:6]
print(top5Similar)


[[1350   65 1224 1046 1029]
 [ 555  592  723  548  505]
 [1432 1416 1385 1132  753]
 ...
 [ 205 1371  446 1261  129]
 [1094 1012  966 1148  980]
 [1287  503   53  571  437]]


In [11]:
print(dataSet[129],"\n")
print(dataSet[205])

this man is average weight and a little shorter than average he has black hair and brown eyes he has a beard coming in so he s kind of scruffy he doesn t like his job he is single and no kids he still lives at home sometimes he steals from places 

he is middle eastern he has black hair and brown eyes he keeps himself pretty clean shaven he has very thick eye brows he has medium length hair he has a big nose he is also pretty tall he likes to spend time with his family he loves his job as a doctor he is married with 2 kids he likes to travel his main hobby is photography he is very outgoing and approachable


## Manhattan distance - TfIdf
too slow to run

In [80]:
manhat = pairwise_distances(TfIdf_dataSet, metric='manhattan')

manhatSorted = numpy.argsort(manhat, axis=1)
top5Similar = manhatSorted[:,1:6]
print(top5Similar)


[[1453 1434  584 1331 1350]
 [ 222 1365 1241 1338  268]
 [ 208 1125  291   56  592]
 ...
 [1371   56  680  592  626]
 [ 894    3 1094  927  739]
 [ 404 1143 1206  540  984]]


In [82]:
print(dataSet[894])
print(dataSet[1094])

this person is 5 2 weighs 180 pounds her shoe size is 6 5 she enjoys reading biking and going to movies she is not married and has three cats that she calls her furbabies she is a teacher so she is very busy
she is fair complected with light freckles she has beautiful large blue eyes and full pink lips she is shy she enjoys reading she is intelligent she is compassionate
