In [1]:
import numpy
import scipy
import scipy.sparse
import sklearn
import sklearn.metrics.pairwise
from sklearn import datasets
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.feature_extraction.text import HashingVectorizer


In [2]:
dataSet = numpy.load("descriptions_cleaned_array.npy")
#dataSet = dataSet[0:3]
#print(dataSet)

# Hash Vectorizer

## Default number of features
Using the Hash vectorizer function which only looks at word counts
Can limit the number of features - will go back to that but start with default

In [3]:
hashVector = HashingVectorizer()
Hash_dataSet = hashVector.transform(dataSet)
print(Hash_dataSet.shape, Hash_dataSet.size,"\n")
#print(Hash_dataSet,"\n")

(1480, 1048576) 46996 



### Cosine Similarity

In [4]:
cossim = sklearn.metrics.pairwise.cosine_similarity(Hash_dataSet)
print(cossim,"\n")
cosineSimilaritySorted = numpy.argsort(cossim, axis=1)
print(cosineSimilaritySorted,"\n")
top5Similar = cosineSimilaritySorted[:,-6:-1]
print(top5Similar)



[[1.         0.19720266 0.08175191 ... 0.23314715 0.12942072 0.31934404]
 [0.19720266 1.         0.16927779 ... 0.27586342 0.11136921 0.22327675]
 [0.08175191 0.16927779 1.         ... 0.29110162 0.11109411 0.12460152]
 ...
 [0.23314715 0.27586342 0.29110162 ... 1.         0.25136748 0.29720128]
 [0.12942072 0.11136921 0.11109411 ... 0.25136748 1.         0.39451112]
 [0.31934404 0.22327675 0.12460152 ... 0.29720128 0.39451112 1.        ]] 

[[1160  327  317 ... 1192  495    0]
 [1285  228   88 ...  268  933    1]
 [ 641  496  334 ...  208 1133    2]
 ...
 [1252   88   91 ...  796 1171 1477]
 [ 496 1011  641 ... 1064  895 1478]
 [ 496  208  915 ...  547  279 1479]] 

[[ 607 1316 1121 1192  495]
 [1242  401  556  268  933]
 [ 181 1174 1051  208 1133]
 ...
 [ 819 1436 1372  796 1171]
 [ 178 1095  967 1064  895]
 [ 163  603  500  547  279]]


This provides the same output as the Count Vectorizer cosine similarity, so may have to change the feature number to see if that does anything.

In [5]:
print(dataSet[932])
print(dataSet[268])

this person seems to tall about 6 feet 3 inch height with thin body build up this person seems to be from lower middle class family and he seems to be slight manipulative or little dishonest
caucasian male with blonde hair and blue eyes has a beard and a mustache he looks geeky kind of grumpy and maybe into technology


### Euclidean Distance

In [6]:
euclid = pairwise_distances(Hash_dataSet, metric='euclidean')
euclidSorted = numpy.argsort(euclid, axis=1)
top5Similar = euclidSorted[:,0:6]
print(top5Similar)

[[   0  495 1192 1121 1316  607]
 [   1  933  268  556  401 1242]
 [   2 1133  208 1051 1174  181]
 ...
 [1477 1171  796 1372 1436  819]
 [1478  895 1064  967 1095  178]
 [1479  279  547  500  603  163]]


In [7]:
print(dataSet[0])
print(dataSet[495])

round face short and overweight likes to wear jeans and sweaters drinks wine at dinner short liberal overweight short hair eats at whole foods does not work our very much
a little chubby and short about 5 4 likes to show off her body so she wears tight lower jeans and crop tops very friendly and humorous outgoing and likes to party alot very responsible when it comes to her job and responsibilities


### Manhattan distance

This took too long to run and unlikely to produce better results

In [ ]:
manhat = pairwise_distances(Hash_dataSet, metric='manhattan')

manhatSorted = numpy.argsort(manhat, axis=1)
top5Similar = manhatSorted[:,0:6]
print(top5Similar)


In [ ]:
print(dataSet[894])
print(dataSet[1094])

## Hash Vectorizer - Limit to 1000 features

In [ ]:
hashVector = HashingVectorizer(n_features=1000)
Hash_dataSet = hashVector.transform(dataSet)
print(Hash_dataSet.shape, Hash_dataSet.size,"\n")
#print(Hash_dataSet,"\n")

### Cosine Similarity

In [ ]:
cossim = sklearn.metrics.pairwise.cosine_similarity(Hash_dataSet)
print(cossim,"\n")
cosineSimilaritySorted = numpy.argsort(cossim, axis=1)
print(cosineSimilaritySorted,"\n")
top5Similar = cosineSimilaritySorted[:,-6:-1]
print(top5Similar)



Now somewhat different values than the Count vectorizer but some still the same

In [ ]:
#print(dataSet[163])
#print(dataSet[602])
#print(dataSet[499])
#print(dataSet[279])
#print(dataSet[546])
##good set except for 499

print(dataSet[815])
print(dataSet[1170])

### Euclidean Distance

In [ ]:
euclid = pairwise_distances(Hash_dataSet, metric='euclidean')
euclidSorted = numpy.argsort(euclid, axis=1)
top5Similar = euclidSorted[:,1:6]
print(top5Similar)


In [ ]:
print(dataSet[401])
print(dataSet[268])

Gives a similar output to the cosine similairty output

### Manhattan distance

Runs faster with less features

In [ ]:
manhat = pairwise_distances(Hash_dataSet, metric='manhattan')

manhatSorted = numpy.argsort(manhat, axis=1)
top5Similar = manhatSorted[:,1:6]
print(top5Similar)


In [ ]:
print(dataSet[894])
print(dataSet[1094])